---

- name: Install base packages
  apt: 
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - ca-certificates
    - apt-transport-https
    - curl
    - software-properties-common
    - python-pip
